export const enum Environment {
  BUCKET_NAME = 'BUCKET_NAME',
  BASE_URL = 'BASE_URL',
  OBJECT_PREFIX = 'OBJECT_PREFIX',
  METADATA_FILENAME = 'METADATA_FILENAME',
  TABLE_NAME = 'TABLE_NAME',
  JSII_ASSEMBLY_FILENAME = 'JSII_ASSEMBLY_FILENAME'
}